- name: install docker
  yum:
    name: docker
    state: present

- name: install python pip for docker-compose
  yum:
    name: python-pip
  when: docker_install_compose == true

- name: install docker-compose
  pip:
    name: docker-compose
  when: docker_install_compose == true

- name: install python docker library
  yum:
    name: docker-python
    state: present

- name: add user to docker group to allow use of docker without sudo
  user:
    name: "{{ ansible_user_id }}"
    groups: dockerroot
    append: yes
  when: docker_sudoless == true
